### ISSUE TITLE
Add-on GearGenMaster buggy

### ISSUE THREAD

**Issue by eiger3970** [serzh272/GearGenMaster#3]
**System Information**
Operating system: Linux Mint 19 Tara 64-bit Kernel Linux 4.15.0-76-generic x86_64 MATE 1.20.1
Graphics card: Advanced Micro Devices [AMD/ATI] Juniper XT [Radeon HD 5770]

**Blender Version**
Broken: v2.79
Worked: (optional)

**Short description of error**
Add-on GearGenMaster buggy in several cases.

**Exact steps for others to reproduce the error**

**1.**
Blender v2.79 > Edit Mode > delete cube > Object Mode > Add > Mesh > GearGenMaster > Add <item> > top right message shows: Select object created by GearGenMaster! > no object in ViewPort.
Solution: delete Cube in Object Mode.

**2.** 
Add-on install is buggy with unclear steps.
Need to install GearGenMaster, then install GearGenMaster-master.

**3.**
Object Mode > Add > Mesh > GearGenMaster appears twice (both functional), however only need GearGenMaster showing once in Mesh choices.

**4.**
Left bottom Menu titled 'Add_<gearTypeAdded>' appears when working on object > disappears is entering another mode or function and doesn't come back.

**5.**
Menu 'Add_Herringbone_Gear' > Deformations > Skewness: degrees works, however in
Menu 'Add_Spur_Gear' (wrong title, as I add Rack) > Skewness: degrees doesn't work, field changes input of 45 (for 45 degrees) to 1.6 mm. Inconsistent with working with the herringbone gear with a set angle of 45 degrees for example. Rack also needs an angle of 45 degrees, not whatever 1.6 mm means?

**6.**
Several other bugs like this, but too numerous to mention. Great add-on, but needs bugs corrected.

**Comment by serzh272** [comment]
1. fixed
2. Only one GearGenMaster file needs to be installed. Before installation, the remaining versions must be removed.
3. see 2
4. These are the features of Blender. Any created objects in Blender are not parametric (as for example in 3ds Max). After creating an object, it can only be edited as a mesh.
5. Temporarily removed this option.
6. Thanks for the feedback. The addon will still be finalized.
